import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import {
  SkbAgentApiWriter,
  getRecentWriterConflicts,
  clearWriterConflicts,
} from "@/lib/chemEln/sync/writer";

/**
 * Data-loss regression: regeneration used to overwrite a synced page unless its
 * content hashed identically to the freshly generated content. Any human edit
 * therefore got clobbered on the next sync. The writer now stamps a
 * generated-hash marker into pages it writes; on the next sync, if the page's
 * current body no longer matches that marker, it was hand-edited and we skip
 * (recording a conflict) instead of destroying the edit.
 */

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

describe("SkbAgentApiWriter — manual-edit guard", () => {
  let writer: SkbAgentApiWriter;
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    clearWriterConflicts();
    writer = new SkbAgentApiWriter({
      apiUrl: "http://localhost:3000",
      apiKey: "k",
      rateLimit: 1000,
      maxRetries: 0,
    });
    fetchMock = vi.fn();
    global.fetch = fetchMock as unknown as typeof fetch;
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("skips and records a conflict when the page was hand-edited since generation", async () => {
    // The body we ORIGINALLY generated, plus its marker.
    const originalBody = "# Suzuki Coupling\n\nGenerated body.";
    const genHash = writer.computeHash(originalBody);
    // The page on the server: human appended a line but the OLD marker remains,
    // so the body no longer matches genHash.
    const handEdited =
      `${originalBody}\n\nIMPORTANT human note: do not raise temp.\n\n<!-- skb:generated ${genHash} -->\n`;

    fetchMock
      // searchPages → one match
      .mockResolvedValueOnce(
        jsonResponse({
          data: [
            {
              id: "page-1",
              title: "Suzuki Coupling",
              icon: null,
              parent_id: null,
              created_at: "2026-01-01",
              updated_at: "2026-01-02",
            },
          ],
        })
      )
      // getPage → returns the hand-edited markdown
      .mockResolvedValueOnce(
        jsonResponse({
          data: {
            id: "page-1",
            title: "Suzuki Coupling",
            icon: null,
            parent_id: null,
            created_at: "2026-01-01",
            updated_at: "2026-01-02",
            markdown: handEdited,
          },
        })
      );

    const newGenerated = "# Suzuki Coupling\n\nRegenerated body with different content.";
    const result = await writer.upsertPage(newGenerated, "eln:EXP-9");

    expect(result.action).toBe("skipped");
    expect(result.pageId).toBe("page-1");
    // Crucially: NO updatePage call (only search + getPage = 2 fetches).
    expect(fetchMock).toHaveBeenCalledTimes(2);

    const conflicts = getRecentWriterConflicts();
    expect(conflicts).toHaveLength(1);
    expect(conflicts[0].pageId).toBe("page-1");
    expect(conflicts[0].tag).toBe("eln:EXP-9");
  });

  it("overwrites when the page still matches the last generated hash (no human edit)", async () => {
    const originalBody = "# Suzuki Coupling\n\nGenerated body.";
    const genHash = writer.computeHash(originalBody);
    const stillGenerated = `${originalBody}\n\n<!-- skb:generated ${genHash} -->\n`;

    fetchMock
      .mockResolvedValueOnce(
        jsonResponse({
          data: [
            {
              id: "page-1",
              title: "Suzuki Coupling",
              icon: null,
              parent_id: null,
              created_at: "2026-01-01",
              updated_at: "2026-01-02",
            },
          ],
        })
      )
      .mockResolvedValueOnce(
        jsonResponse({
          data: {
            id: "page-1",
            title: "Suzuki Coupling",
            icon: null,
            parent_id: null,
            created_at: "2026-01-01",
            updated_at: "2026-01-02",
            markdown: stillGenerated,
          },
        })
      )
      // updatePage
      .mockResolvedValueOnce(
        jsonResponse({ data: { id: "page-1", updated_at: "2026-01-03" } })
      );

    const newGenerated = "# Suzuki Coupling\n\nRegenerated body, machine-driven.";
    const result = await writer.upsertPage(newGenerated, "eln:EXP-9");

    expect(result.action).toBe("updated");
    expect(fetchMock).toHaveBeenCalledTimes(3); // search + getPage + updatePage
    expect(getRecentWriterConflicts()).toHaveLength(0);
  });

  it("treats a legacy page with no marker as safe to overwrite (backward compatible)", async () => {
    const legacyNoMarker = "# Suzuki Coupling\n\nOld content, never generated by us.";

    fetchMock
      .mockResolvedValueOnce(
        jsonResponse({
          data: [
            {
              id: "page-1",
              title: "Suzuki Coupling",
              icon: null,
              parent_id: null,
              created_at: "2026-01-01",
              updated_at: "2026-01-02",
            },
          ],
        })
      )
      .mockResolvedValueOnce(
        jsonResponse({
          data: {
            id: "page-1",
            title: "Suzuki Coupling",
            icon: null,
            parent_id: null,
            created_at: "2026-01-01",
            updated_at: "2026-01-02",
            markdown: legacyNoMarker,
          },
        })
      )
      .mockResolvedValueOnce(
        jsonResponse({ data: { id: "page-1", updated_at: "2026-01-03" } })
      );

    const result = await writer.upsertPage(
      "# Suzuki Coupling\n\nNew content",
      "eln:EXP-9"
    );

    expect(result.action).toBe("updated");
    expect(getRecentWriterConflicts()).toHaveLength(0);
  });

  it("stamps a generated-hash marker into newly created pages", async () => {
    fetchMock
      // searchPages → no match
      .mockResolvedValueOnce(jsonResponse({ data: [] }))
      // createPage
      .mockResolvedValueOnce(
        jsonResponse({
          data: { id: "new-1", title: "T", created_at: "2026-01-01" },
        })
      );

    await writer.upsertPage("# T\n\nbody", "eln:EXP-1", { title: "T" });

    // The create call body must carry the marker.
    const createCall = fetchMock.mock.calls[1];
    const sentBody = JSON.parse(createCall[1].body as string);
    expect(sentBody.markdown).toMatch(/<!--\s*skb:generated\s+[a-f0-9]{32}\s*-->/);
  });
});
